apiVersion: v1
kind: Service
metadata:
  name: kubeflare-flask-service
spec:
  selector:
    app: kubeflare-flask
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer  # Can override per environment later
